import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Quicksand } from "next/font/google";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const quicksand = Quicksand({
	subsets: ["latin"], // välj vilka subset du behöver
	weight: ["300", "400", "500", "600", "700"], // välj vikter
	variable: "--font-quicksand", // gör den tillgänglig som CSS-variabel
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="sv" className={quicksand.variable}>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<Navbar />
				<div className="wrapper">{children}</div>
			</body>
		</html>
	);
}
